INSERT INTO "public"."datatable_columns" ("id", "name", "author", "status", "description", "created_at", "updated_at", "table", "order", "type", "value") VALUES ('1', 'period', NULL, NULL, NULL, '2018-10-19', NULL, '1', '0', NULL, 'Период'),
('2', 'rub_rates', NULL, NULL, NULL, '2018-10-19', NULL, '1', '0', NULL, 'RUB'),
('3', 'usd_rates', NULL, NULL, NULL, '2018-10-19', NULL, '1', '0', NULL, 'USD'),
('4', 'eur_rates', NULL, NULL, NULL, '2018-10-19', NULL, '1', '0', NULL, 'EUR'),
('5', 'rub_risk', NULL, NULL, NULL, '2018-10-19', NULL, '1', '0', NULL, 'RUB'),
('6', 'usd_risk', NULL, NULL, NULL, '2018-10-19', NULL, '1', '0', NULL, 'USD'),
('7', 'eur_risk', NULL, NULL, NULL, '2018-10-19', NULL, '1', '0', NULL, 'EUR'),
('8', 'mesto', NULL, NULL, NULL, NULL, NULL, '2', '1', NULL, 'Место'),
('9', 'dolzhnost', NULL, NULL, NULL, NULL, NULL, '2', '2', NULL, 'Должность'),
('10', 'to', NULL, NULL, NULL, NULL, NULL, '2', '3', NULL, 'Тер.офис'),
('11', 'prefix', NULL, NULL, NULL, NULL, NULL, '2', '4', NULL, 'Префикс'),
('12', 'fio', NULL, NULL, NULL, NULL, NULL, '2', '5', NULL, 'ФИО'),
('13', 'kpi', NULL, NULL, NULL, NULL, NULL, '2', '6', NULL, 'Бизнес KPI'),
('14', 'mesto', NULL, NULL, NULL, NULL, NULL, '3', '1', NULL, ' Место'),
('15', 'to', NULL, NULL, NULL, NULL, NULL, '3', '2', NULL, 'Тер.офис'),
('16', 'prefix', NULL, NULL, NULL, NULL, NULL, '3', '3', NULL, 'prefix'),
('17', 'fio', NULL, NULL, NULL, NULL, NULL, '3', '4', NULL, 'ФИО'),
('18', 'kpi', NULL, NULL, NULL, NULL, NULL, '3', '5', NULL, 'Бизнес KPI'),
('19', 'mesto', NULL, NULL, NULL, NULL, NULL, '4', '1', NULL, 'Место'),
('20', 'to', NULL, NULL, NULL, NULL, NULL, '4', '2', NULL, 'Тер.офис'),
('21', 'do', NULL, NULL, NULL, NULL, NULL, '4', '3', NULL, 'Доп.офис'),
('22', 'fio', NULL, NULL, NULL, NULL, NULL, '4', '4', NULL, 'ФИО'),
('23', 'kpi', NULL, NULL, NULL, NULL, NULL, '4', '5', NULL, 'Бизнес KPI'),
('24', 'mesto', NULL, NULL, NULL, NULL, NULL, '5', '1', NULL, 'Место'),
('25', 'to', NULL, NULL, NULL, NULL, NULL, '5', '2', NULL, 'Тер.офис'),
('26', 'fio', NULL, NULL, NULL, NULL, NULL, '5', '3', NULL, 'ФИО'),
('27', 'kpi', NULL, NULL, NULL, NULL, NULL, '5', '4', NULL, 'Бизнес KPI'),
('28', 'mesto', NULL, NULL, NULL, NULL, NULL, '6', '1', NULL, 'Место'),
('29', 'to', NULL, NULL, NULL, NULL, NULL, '6', '2', NULL, 'Тер.офис'),
('30', 'fio', NULL, NULL, NULL, NULL, NULL, '6', '3', NULL, 'ФИО'),
('31', 'kpi', NULL, NULL, NULL, NULL, NULL, '6', '4', NULL, 'Бизнес KPI'),
('32', 'mesto', NULL, NULL, NULL, NULL, NULL, '7', '1', NULL, 'Место'),
('33', 'to', NULL, NULL, NULL, NULL, NULL, '7', '2', NULL, 'Тер.офис'),
('34', 'fio', NULL, NULL, NULL, NULL, NULL, '7', '3', NULL, 'ФИО'),
('35', 'kpi', NULL, NULL, NULL, NULL, NULL, '7', '4', NULL, 'Бизнес KPI');
